name = "mi-xian-ju-api"
main = "src/main.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[[kv_namespaces]]
binding = "DATA_KV"
id = "3ea5f9c2de724a25b05f1d270aa5657b"
# preview_id = "3ea5f9c2de724a25b05f1d270aa5657b"

# [[d1_databases]]
# binding = "DB"
# database_name = "mi-xian-ju"
# database_id = "REPLACE_WITH_D1_DATABASE_ID"

[vars]
APP_NAME = "芈仙居 API"
